/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
public class Problem2 {
    public static void main(String[] args) {
        int limit = 4_000_000;
        int var1 = 1;
        int var2 = 2;
        int sumeven = var2;//Se comienza en 2 porque es la primera suma de la serie Fibonacci

        while (var1 + var2 < limit) {
            int next = var1 + var2;
            var1 = var2;
            var2 = next;

            if (next % 2 == 0) {//Condicion que me permite comprobar si el termino a sumar es "even-valued"
                sumeven += next;
            }
        }
        System.out.println(sumeven);
    }
}
