# /*
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
# */
var1 = 0
var2 = 1
sum = 0
sum_even_value = 0 

while (sum < 4000000):
    sum = var1 + var2
    if (sum %2 == 0):
        sum_even_value +=sum
    var1 = var2
    var2 = sum

print(sum_even_value)